name: Bug Report
description: File a bug report
labels: ["defect", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Check for existing issues
      description: Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.
      options:
        - label: Completed
          required: true
  - type: textarea
    attributes:
      label: Describe the bug / provide steps to reproduce it
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        In v0.68.0 and later, you can open a bug report, with the environment data pre-filled, by using the `file bug report` command.
        For versions prior to that, run the command below in a terminal and paste the output (requires Zed CLI: Zed > Zed menu > `Install CLI`)
      value: echo $(zed --version) "\n"macOS $(sw_vers -productVersion) "\n"architecture $(uname -m)
    validations:
      required: true
  - type: textarea
    attributes:
      label: If applicable, add mockups / screenshots to help explain present your vision of the feature
      description: Drag issues into the text input below
    validations:
      required: false
  - type: textarea
    attributes:
      label: If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue
      description: Drag Zed.log into the text input below
    validations:
      required: false
