contact_links:
  - name: Top-Ranking Issues
    url: https://github.com/zed-industries/feedback/issues/52
    about: See an overview of the most popular Zed issues
  - name: Platform Support
    url: https://github.com/zed-industries/feedback/issues/174
    about: A quick note on platform support
  - name: Postive Feedback
    url: https://github.com/zed-industries/feedback/issues/140
    about: A central location for kind words about Zed