name: Language Support
description: Request language support
labels: ["enhancement", "language / framework", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Check for existing issues
      description: Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.
      options:
        - label: Completed
          required: true
  - type: input
    attributes:
      label: Language
      description: What language do you want support for?
      placeholder: HTML
    validations:
      required: true
  - type: input
    attributes:
      label: Tree Sitter Parser
      description: If applicable, provide a link to the appropriate tree sitter parser
      placeholder: https://github.com/tree-sitter/tree-sitter-html
    validations:
      required: false
  - type: input
    attributes:
      label: Language Server
      description: If applicable, provide a link to the appropriate language server
      placeholder: https://github.com/Microsoft/vscode/tree/main/extensions/html-language-features/server
    validations:
      required: false
  - type: textarea
    attributes:
      label: Misc notes
      description: Provide any additional things the team should consider when adding support for this language
    validations:
      required: false
